//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message_SuperNova {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message_SuperNova() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Message_SuperNova", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không đủ tiền trong tài khoản, bạn cần ít nhất {0} để có thể quay..
        /// </summary>
        internal static string BalanceError {
            get {
                return ResourceManager.GetString("BalanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn đang chơi game ở thiết bị khác..
        /// </summary>
        internal static string DuplicatePlayGame {
            get {
                return ResourceManager.GetString("DuplicatePlayGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang quay, mời bạn đợi một chút để tiếp tục quay..
        /// </summary>
        internal static string DuplicateSpin {
            get {
                return ResourceManager.GetString("DuplicateSpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang chơi game, bạn phải chơi xong mới tiếp tục quay được. Mời bạn chơi tiếp..
        /// </summary>
        internal static string Error600 {
            get {
                return ResourceManager.GetString("Error600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số line {0} bạn chọn không hợp lệ, bạn chỉ được chọn số line từ {1} đến {2}..
        /// </summary>
        internal static string LinesError {
            get {
                return ResourceManager.GetString("LinesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hết phiên đăng nhập, mời bạn đăng nhập lại.
        /// </summary>
        internal static string NotAuthen {
            get {
                return ResourceManager.GetString("NotAuthen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hết phiên chơi, mời thử lại.
        /// </summary>
        internal static string NotPlay {
            get {
                return ResourceManager.GetString("NotPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang không ở trong Game Bonus.
        /// </summary>
        internal static string NotPlayBonus {
            get {
                return ResourceManager.GetString("NotPlayBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rất tiếc hệ thống của chúng tôi đang bận! Mời bạn thử lại sau!.
        /// </summary>
        internal static string SpinError {
            get {
                return ResourceManager.GetString("SpinError", resourceCulture);
            }
        }
    }
}
