//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuckySpinSanh.PortalCaptcha {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PortalCaptcha.captchaSoap")]
    public interface captchaSoap {
        
        // CODEGEN: Generating message contract since element name captcha from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProxyCheckCaptcha", ReplyAction="*")]
        LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaResponse ProxyCheckCaptcha(LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProxyCheckCaptcha", ReplyAction="*")]
        System.Threading.Tasks.Task<LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaResponse> ProxyCheckCaptchaAsync(LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProxyCheckCaptchaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProxyCheckCaptcha", Namespace="http://tempuri.org/", Order=0)]
        public LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaRequestBody Body;
        
        public ProxyCheckCaptchaRequest() {
        }
        
        public ProxyCheckCaptchaRequest(LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProxyCheckCaptchaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string captcha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public ProxyCheckCaptchaRequestBody() {
        }
        
        public ProxyCheckCaptchaRequestBody(string captcha, string token) {
            this.captcha = captcha;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProxyCheckCaptchaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProxyCheckCaptchaResponse", Namespace="http://tempuri.org/", Order=0)]
        public LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaResponseBody Body;
        
        public ProxyCheckCaptchaResponse() {
        }
        
        public ProxyCheckCaptchaResponse(LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProxyCheckCaptchaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ProxyCheckCaptchaResult;
        
        public ProxyCheckCaptchaResponseBody() {
        }
        
        public ProxyCheckCaptchaResponseBody(bool ProxyCheckCaptchaResult) {
            this.ProxyCheckCaptchaResult = ProxyCheckCaptchaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface captchaSoapChannel : LuckySpinSanh.PortalCaptcha.captchaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class captchaSoapClient : System.ServiceModel.ClientBase<LuckySpinSanh.PortalCaptcha.captchaSoap>, LuckySpinSanh.PortalCaptcha.captchaSoap {
        
        public captchaSoapClient() {
        }
        
        public captchaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public captchaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public captchaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public captchaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaResponse LuckySpinSanh.PortalCaptcha.captchaSoap.ProxyCheckCaptcha(LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaRequest request) {
            return base.Channel.ProxyCheckCaptcha(request);
        }
        
        public bool ProxyCheckCaptcha(string captcha, string token) {
            LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaRequest inValue = new LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaRequest();
            inValue.Body = new LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaRequestBody();
            inValue.Body.captcha = captcha;
            inValue.Body.token = token;
            LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaResponse retVal = ((LuckySpinSanh.PortalCaptcha.captchaSoap)(this)).ProxyCheckCaptcha(inValue);
            return retVal.Body.ProxyCheckCaptchaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaResponse> LuckySpinSanh.PortalCaptcha.captchaSoap.ProxyCheckCaptchaAsync(LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaRequest request) {
            return base.Channel.ProxyCheckCaptchaAsync(request);
        }
        
        public System.Threading.Tasks.Task<LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaResponse> ProxyCheckCaptchaAsync(string captcha, string token) {
            LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaRequest inValue = new LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaRequest();
            inValue.Body = new LuckySpinSanh.PortalCaptcha.ProxyCheckCaptchaRequestBody();
            inValue.Body.captcha = captcha;
            inValue.Body.token = token;
            return ((LuckySpinSanh.PortalCaptcha.captchaSoap)(this)).ProxyCheckCaptchaAsync(inValue);
        }
    }
}
